---

default: &default
  # socket_ip: 127.0.0.1
  socket_ip: 0.0.0.0
  socket_port: 21314
  #logic_ip: 127.0.0.1
  logic_ip: 0.0.0.0
  logic_port: 56789

  transports:
    - polling
    - websocket #服务器端尽量开启websocket, 当有大量客户端断开时,如果客户端与服务器通过websocket连接的话,可以保证服务器回调函数能可靠的调用(不存在回调不执行的情况)
  pingInterval: 20000
  pingTimeout: 10000


  redis_address: '127.0.0.1:6379'
  redis_password:
#    - 127.0.0.1:10010
#    - 127.0.0.1:10020
  redis_prefix: p_
  redis_db: 0

  key_reg: '^[\\\w.\\\d\-$#/]+$'                                         #命名空间 房间  userid  uuid 正则

  room_activity_broadcast: true                                                    #进入或者离开房间时是否需要向房间广播该变动
  worker_message_timeout: 5000                                                     #消息发送之后延迟多长时间进行离线推送(android|ios)

  push_message_expire: 1                                                           #默认每条消息的失效时间，单位小时
  push_message_max_expire: 10                                                      #每条消息的失效时间，最大值，单位小时
  push_message_list_max_limit: 1000                                                #每个命名空间可以查看到的分页消息总数(只是用于调试或者简单查看历史推送记录)
  report_online_list_max_limit: 1000                                               #统计在线信息时如果查看详情可以返回的最大信息数(房间名，userid，uuid)
  report_push_ack_detail_max_limit: 1000                                           #统计推送结果时可以返回的ack客户端总数
  android_unread_message_list_max_limit: 100                                       #每一个android设备可以保存未读消息总数
  client_legacy_expire: 240                                                        #客户端在最后一次上线之后多长时间会被服务器清除数据，单位小时
  client_push_interval: 1                                                          #客户端发起推送的时间间隔，时间单位秒

  room_max_length: 100
  userid_max_length: 100
  uuid_max_length: 100
  namespace_max_length: 50

  emit_msg_pick_key: true                                                          #在线推送的消息是否过滤不必要的字段

  apns_aps_alert: '通知'
  apns_payload_size: 4000

  admin_name: admin
  admin_passwd: 123456

  log_path:

dev:
  << : *default

  transports:
    - websocket

sit:
  << : *default

  redis_address: '10.88.26.213:6379'
  redis_db: 5
